### ISSUE TITLE
Building ISO gets stuck on converting txt files

### ISSUE THREAD

**Issue by Brawdogger** [weathondev/SingstarCreatorTutorial#7]
![txtfilestuck](https://github.com/user-attachments/assets/9129d14a-78ee-43fe-bbd5-1a7de304ba95)
After adding multiple songs to a list, hitting the create DVD/ISO button will often result in the process getting stuck on converting the txt files and will no longer progress. Am able to confirm that this is not due to the txt files being invalid as trying to create an ISO with just the suspected song works

**Comment by weathondev** [comment]
Usually this is still related to the txts or even music, video files etc. Can you upload me the all the files you want on one iso? Then I can troubleshoot myself.

**Comment by Brawdogger** [comment]
https://drive.google.com/file/d/1LNB7HjbQEDEeZUXMY1mW1lhwKYYLpBjs/view?usp=sharing

I might not send through all of the songs that I was planning on adding as I've got about 100+ however can provide these as an example. Was able to replicate the same error as above with these

**Comment by weathondev** [comment]
Perfect. i'll let you know as soon as i get the time to look at it, today's definitely busy but homeoffice tomorrow so fingers crossed.

**Comment by Brawdogger** [comment]
All good, gave Minor the same list of songs and he got the same issue as well. Let me know how it goes for you and if you have any luck troubleshooting this as this issue is completely blocking my project right now and may possibly have to resort to coding my own singstar creator if it isn't possible to fix

**Comment by weathondev** [comment]
Hey!
I think i found something..
Out of the 15 songs you've sent me, 5 did not work for me.
The 5 songs that didn't work:
- Perfect
- You're welcome
- Cruel Summer
- Something just like this
- All star

4 of these songs had negative timestamps (all except all star), i removed the negative  timestamps and since then these are working:
- Perfect
- Something just like this

For the Song 'all star' i noticed that the VIDEO GAP number contained a comma (2,8 instead of 2.8), i changed that one, and since then it works.

These are still not working (no idea yet):
- You're welcome
- Cruel Summer

**Comment by weathondev** [comment]
Yep i'll definitely update the repo once this round of investigation is done. If you want, feel free to create a PR.
I tried a bit further for these two songs but couldn't find anything more. Btw the negative timestamps thing is something that chatgpt told me to look into :D

**Comment by weathondev** [comment]
Okay i found it :) 
In both of these songs some lines start with an 'R' instead e.g. of an 'F' or a '*' like in other files.
I suspect that this is an annotation that the old singstar doesn't know, i'm not sure what it stands for. i found these annotations here, so R could maybe be replaced with one of these: https://nocturnalstalker.wordpress.com/2017/06/26/ultrastar-text-file-formatting/

**Comment by Brawdogger** [comment]
Big thank you for looking into this and finding these issues, definitely have saved my ass for this project I was working on. As I was planning on import over 100 songs, I might go ahead and write a python script to scan these txt files automatically and highlight/fix any of these errors that singstar creator misses. Will upload it to github if it ends up working and can add it to the guide if you want
